# Discord values (Game Deals) [Bot Discord]
DISCORD_CHANNEL_ID = "<DISCORD_CHANNEL_ID>"
DISCORD_TOKEN = "<DISCORD_TOKEN>"

# Reddit values (GameDeals) [Bot Reddit]
REDDIT_CLIENT_ID = "<REDDIT_CLIENT_ID>"
REDDIT_CLIENT_SECRET = "<REDDIT_CLIENT_SECRET>"
REDDIT_PASSWORD = "<REDDIT_PASSWORD>"
REDDIT_USER_AGENT = "GameDealsBot"
REDDIT_USERNAME = "<REDDIT_USERNAME>"