# Discord values (Game Deals) [Bot Discord]
DISCORD_CHANNEL_ID = "<DISCORD_CHANNEL_ID>"
DISCORD_TOKEN = "NzA2NDMzOTQzMjgwNDE4ODE3.XrIJeA.zsv3aDLSL1Mwg7K_-Uf6sWO5o3w"

# Reddit values (Gratis) [Bot Reddit]
REDDIT_CLIENT_ID = "PWzL26MwPoKw_g"
REDDIT_CLIENT_SECRET = "9hy-8izjQxrJQErjcQ4-RwkDKlU"
REDDIT_PASSWORD = "<REDDIT_PASSWORD>"
REDDIT_USER_AGENT = "Gratisv1"
REDDIT_USERNAME = "<REDDIT_USERNAME>"
